name: mmo
main: com.server.Main
version: 0.0.1
api-version: 1.20
description: MMO plugin for Minecraft servers
depend: [Geyser-Spigot]

commands:
  menu:
    description: Opens the MMO menu
    usage: /menu
    aliases: [mmomenu]
  profile:
    description: Opens the profile selector
    usage: /profile
    aliases: [mprofile]
  stats:
    description: Opens the stats menu
    usage: /stats
    aliases: [mmostats]   
  cosmetics:
    description: Opens the cosmetic equipment menu
    usage: /cosmetics
    aliases: [costume, outfits]
  givehat:
    description: Gives a witch hat cosmetic
    usage: /givehat
    aliases: [witchhat]
  giveitem:
    description: Gives a custom item to a player
    usage: /giveitem <itemname> [player]
    aliases: [customitem, ci]
  debugmode:
    description: Toggle debug mode for the MMO plugin
    usage: /debugmode
    permission: mmo.admin
  fly:
    description: Toggle flight mode for yourself or another player
    usage: /fly [player] [on|off]
    permission: mmo.admin.fly
    aliases: [togglefly]
  balance:
    description: Check your currency balances
    usage: /balance [currency]
    aliases: [bal, money]
  currency:
    description: Manage currencies (admin)
    usage: /currency <give|take|set> <player> <amount> <type>
    permission: mmo.admin.currency
  pay:
    description: Send currency to another player
    usage: /pay <player> <amount> [currency]
  confirm:
    description: Confirm a pending transaction
    usage: /confirm
  cancel:
    description: Cancel a pending transaction
    usage: /cancel

permissions:
  mmo.admin:
    description: Grants access to administrative commands
    default: op
  mmo.admin.fly:
    description: Allows toggling flight mode for self and others
    default: op
  mmo.admin.currency:
    description: Allows managing player currencies
    default: op