name: mmo
main: com.server.Main
version: 0.0.1
api-version: 1.20
description: MMO plugin for Minecraft servers
depend: [ModelEngine]
softdepend: [Geyser]

commands:
  menu:
    description: Opens the MMO menu
    usage: /menu
    aliases: [mmomenu]
  profile:
    description: Opens the profile selector
    usage: /profile
    aliases: [mprofile]
  stats:
    description: Opens the stats menu
    usage: /stats
    aliases: [mmostats]   
  cosmetics:
    description: Opens the cosmetic equipment menu
    usage: /cosmetics
    aliases: [costume, outfits]
  givehat:
    description: Gives a witch hat cosmetic
    usage: /givehat
    aliases: [witchhat]
  giveitem:
    description: Gives a custom item to a player
    usage: /giveitem <itemname> [player]
    aliases: [customitem, ci]
  debugmode:
    description: Toggle debug mode for specific systems or all systems
    usage: /debugmode [system|list]
    permission: mmo.admin
  fly:
    description: Toggle flight mode for yourself or another player
    usage: /fly [player] [on|off]
    permission: mmo.admin.fly
    aliases: [togglefly]
  balance:
    description: Check your currency balances
    usage: /balance [currency]
    aliases: [bal, money]
  currency:
    description: Manage currencies (admin)
    usage: /currency <give|take|set> <player> <amount> <type>
    permission: mmo.admin.currency
  pay:
    description: Send currency to another player
    usage: /pay <player> <amount> [currency]
  confirm:
    description: Confirm a pending transaction
    usage: /confirm
  cancel:
    description: Cancel a pending transaction
    usage: /cancel
  spawnmob:
    description: Spawn a custom mob
    usage: /spawnmob <type>
    permission: mmo.spawnmob
  animdebug:
    description: Debug custom mob animations
    usage: /animdebug <animation> [entityType]
    permission: mmo.admin
  skills:
    description: Opens the skills menu
    usage: /skills
    aliases: [skill, mmoskills]
  adminstats:
    description: Admin command to manage player stats
    usage: /<command> <player> <stat> <value|default> OR /<command> <reset|list> <player>
    permission: mmo.admin.stats
    aliases: [astats]
  admintokens:
    description: Admin command to manage player skill tokens
    usage: /<command> <player> <skill> <amount> OR /<command> <reset|list> <player>
    permission: mmo.admin.tokens
    aliases: [atokens]
  adminskills:
    description: Admin command to manage player skill levels and XP
    usage: /<command> <player> <skill> <level|xp> <value> OR /<command> <reset|list> <player>
    permission: mmo.admin.skills
    aliases: [askills, askill]
  crystal:
    description: Manage crystals for the GemCarving skill
    usage: /crystal <summon|remove|give> [arguments]
    permission: mmo.command.crystal
  gemtool:
    description: Get a gem carving tool
    usage: /gemtool [player]
    permission: mmo.command.gemtool
  mmonpc:
    description: Create and manage NPCs for the MMO system
    usage: /mmonpc <create|remove|list> [args]
    permission: mmo.admin.npc
    aliases: [mmopnpc, mnpc]
  adminprofile:
    description: Admin command to manage player profile levels and XP
    usage: /<command> <player> <level|xp|add> <value> OR /<command> <list|info> <player>
    permission: mmo.admin.profile
    aliases: [aprofile, adminpro]
  crafting:
    description: Open the custom crafting table
    usage: /crafting
    aliases: [craft, workbench]
  adminfurnace:
    description: Administrative commands for custom furnaces
    usage: /adminfurnace <create|remove|list|info|give|settemp|addfuel|debug>
    permission: mmo.admin.furnace
    aliases: [afurnace, adminf]
  adminenchanting:
    description: Administrative commands for custom enchanting system
    usage: /adminenchanting <giverune|testlevel|listbooks|debug> [args]
    permission: mmo.admin.enchanting
    aliases: [aenchant, adminench]

permissions:
  mmo.admin:
    description: Grants access to administrative commands
    default: op
  mmo.admin.fly:
    description: Allows toggling flight mode for self and others
    default: op
  mmo.admin.currency:
    description: Allows managing player currencies
    default: op
  mmo.spawnmob:
    description: Allows to spawn custom entities
    default: op
  mmo.animdebug:
    description: Grants access to animation debug commands
    default: op
  mmo.admin.stats:
    description: Allows managing player stats
    default: op
  mmo.admin.tokens:
    description: Allows managing player skill tokens
    default: op
  mmo.admin.tokens.showempty:
    description: Shows skills with 0 tokens in token listings
    default: op
  mmo.admin.skills:
    description: Allows managing player skill levels and XP
    default: op
  mmo.command.crystal:
    description: Manage crystals for the GemCarving skill
    default: op
  mmo.command.gemtool:
    description: Get a gem carving tool
    default: op
  mmo.admin.npc:
    description: Allows creating and managing NPCs
    default: op
  mmo.admin.profile:
    description: Allows managing player profile levels and XP
    default: op
  mmo.admin.furnace:
    description: Administrative commands for custom furnaces
    default: op
  mmo.admin.enchanting:
    description: Administrative commands for custom enchanting system
    default: op
  